[policy_module]
operator_num = 1
[[policy_module.create_entry]]
    key_name = "_policy_module:init:accept_all_tasks"
    value = "true"

[remote_storage]
operator_num = 1

[remote_command]
operator_num = 1

[registry]
operator_num = 1
start_after = ["policy_module", "remote_storage"]
[[registry.create_entry]]
    key_name = "_registry:init:use_default_registry"
    value = "false"

[telegram_bot]
operator_num = 1
[[telegram_bot.create_entry]]
    key_name = "tg_bot:bot_token"
    value = ""
[[telegram_bot.create_entry]]
    key_name = "tg_bot:chat_id"
    value = ""
