[policy_module]
operator_num = 1
[[policy_module.create_entry]]
key_name = "_policy_module:init:accept_all_tasks"
value = "true"

[remote_storage]
operator_num = 1

[remote_command]
operator_num = 1

[registry]
operator_num = 1
start_after = [ "policy_module", "remote_storage" ]
[[registry.create_entry]]
key_name = "_registry:init:registry_addr"
value = ""
[[registry.create_entry]]
key_name = "_registry:init:registry_jwt"
value = ""
