on:
  release:
    types: [released]

name: Build

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Pack
        run: |
          cp target/x86_64-unknown-linux-gnu/release/colink-server ./
          tar -zcvf colink-server-linux-x86_64.tar.gz colink-server README.md user_init_config.template.toml
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: colink-server-linux-x86_64.tar.gz
          asset_name: colink-server-linux-x86_64.tar.gz
          asset_content_type: application/tar+gzip
